
services:
  web:
    container_name: first-vue-app
    build:
      context: .
    command: http-server dist
    ports:
      - 8091:8080
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
